"""create initial tables

Revision ID: 18e68376a845
Revises: 
Create Date: 2026-10-06 11:31:32.084163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18e68376a845'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('name', name=op.f('uq_companies_name'))
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position_type', sa.Enum('backend', 'frontend', 'fullstack', 'devops', 'data', 'qa', 'other', name='positiontype', native_enum=False, length=30), nullable=False),
    sa.Column('level', sa.Enum('intern', 'junior', 'mid', name='level', native_enum=False, length=30), server_default='junior', nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'student', name='employmenttype', native_enum=False, length=30), server_default='full_time', nullable=False),
    sa.Column('work_mode', sa.Enum('onsite', 'hybrid', 'remote', name='workmode', native_enum=False, length=30), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.Enum('linkedin', 'company_site', 'referral', 'job_board', 'recruiter', 'other', name='source', native_enum=False, length=30), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('saved', 'applied', 'screening', 'assignment', 'technical', 'final', 'offer', 'accepted', 'declined', 'rejected', 'withdrawn', 'ghosted', name='status', native_enum=False, length=30), server_default='saved', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name=op.f('ck_applications_salary_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_applications_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_company_id'), 'applications', ['company_id'], unique=False)
    op.create_index('ix_applications_skills', 'applications', ['skills'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_table('application_contacts',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('recruiter', 'referrer', 'hiring_manager', 'interviewer', 'other', name='contactrole', native_enum=False, length=30), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_contacts_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_application_contacts_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'contact_id', name=op.f('pk_application_contacts'))
    )
    op.create_table('status_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('saved', 'applied', 'screening', 'assignment', 'technical', 'final', 'offer', 'accepted', 'declined', 'rejected', 'withdrawn', 'ghosted', name='status', native_enum=False, length=30), nullable=True),
    sa.Column('to_status', sa.Enum('saved', 'applied', 'screening', 'assignment', 'technical', 'final', 'offer', 'accepted', 'declined', 'rejected', 'withdrawn', 'ghosted', name='status', native_enum=False, length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_status_changes_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_changes'))
    )
    op.create_index('ix_status_changes_application_changed', 'status_changes', ['application_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_status_changes_application_changed', table_name='status_changes')
    op.drop_table('status_changes')
    op.drop_table('application_contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index('ix_applications_skills', table_name='applications', postgresql_using='gin')
    op.drop_index(op.f('ix_applications_company_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('companies')
    # ### end Alembic commands ###
